[App]
port = 3000

[App.database]
mongo_url = "mongodb://admin:password@localhost:27018/?authMechanism=DEFAULT&authSource=admin"

[App.logger]
enabled = true
level = "info"

[App.token]
jwt_secret = "Zr4u7x!A%D*G-JaNdRgUkXp2s5v8y/B?"
jwt_lifetime = '30d'